[hls]
relative_roots=C:/Users/rodrigofonseca/Lab1/hls_component
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=stream_matmul/compute_k 
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=stream_matmul/init_c_i  
syn.directive.loop_flatten=stream_matmul/read_a_i  
syn.directive.loop_flatten=stream_matmul/read_b_i  
syn.directive.loop_flatten=stream_matmul/write_c_i  


