

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_U"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_1_U"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_2_U"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_3_U"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_U"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_1_U"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_2_U"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_3_U"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.C_U"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187.fadd_32ns_32ns_32_5_full_dsp_1_U18"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187.fmul_32ns_32ns_32_4_max_dsp_1_U19"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U"},
	{"ID" : "23", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_stream_V_data_V_U"},
	{"ID" : "24", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_stream_V_keep_V_U"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_stream_V_strb_V_U"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_stream_V_last_V_U"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_stream_V_data_V_U"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_stream_V_keep_V_U"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_stream_V_strb_V_U"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_stream_V_last_V_U"}]}
set DependenceCheckSize 0
