

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_U"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_1_U"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_2_U"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_3_U"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_U"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_1_U"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_2_U"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_3_U"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.C_U"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.C_1_U"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.C_2_U"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.C_3_U"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285.sparsemux_9_2_32_1_1_U38"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_stream_matmul_Pipeline_compute_k_fu_317"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_stream_matmul_Pipeline_compute_k_fu_317.mul_16s_16s_32_1_1_U21"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_stream_matmul_Pipeline_compute_k_fu_317.mul_16s_16s_32_1_1_U22"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_stream_matmul_Pipeline_compute_k_fu_317.mul_16s_16s_32_1_1_U23"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_stream_matmul_Pipeline_compute_k_fu_317.mul_16s_16s_32_1_1_U24"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_stream_matmul_Pipeline_compute_k_fu_317.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_32_1_1_U48"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_stream_V_data_V_U"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_stream_V_keep_V_U"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_stream_V_strb_V_U"},
	{"ID" : "33", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_stream_V_last_V_U"},
	{"ID" : "34", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_stream_V_data_V_U"},
	{"ID" : "35", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_stream_V_keep_V_U"},
	{"ID" : "36", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_stream_V_strb_V_U"},
	{"ID" : "37", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_stream_V_last_V_U"}]}
set DependenceCheckSize 0
