// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="stream_matmul_stream_matmul,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.060000,HLS_SYN_LAT=190314,HLS_SYN_TPT=none,HLS_SYN_MEM=12,HLS_SYN_DSP=0,HLS_SYN_FF=851,HLS_SYN_LUT=2617,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module stream_matmul (
        ap_clk,
        ap_rst_n,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] num_k_tiles;
wire   [31:0] select_ln112_fu_355_p3;
reg   [31:0] select_ln112_reg_518;
wire   [31:0] select_ln112_1_fu_378_p3;
reg   [31:0] select_ln112_1_reg_524;
wire    ap_CS_fsm_state2;
wire   [31:0] add_ln112_fu_394_p2;
reg   [31:0] add_ln112_reg_532;
wire    ap_CS_fsm_state3;
wire   [4:0] add_ln145_fu_406_p2;
reg   [4:0] add_ln145_reg_540;
wire    ap_CS_fsm_state7;
wire   [3:0] trunc_ln145_fu_412_p1;
reg   [3:0] trunc_ln145_reg_545;
wire   [4:0] add_ln147_fu_426_p2;
reg   [4:0] add_ln147_reg_554;
wire    ap_CS_fsm_state8;
reg   [5:0] C_addr_reg_559;
reg   [5:0] C_1_addr_reg_564;
reg   [5:0] C_2_addr_reg_569;
reg   [5:0] C_3_addr_reg_574;
wire   [3:0] trunc_ln147_fu_457_p1;
reg   [3:0] trunc_ln147_reg_579;
wire    ap_CS_fsm_state9;
wire   [1:0] trunc_ln147_1_fu_461_p1;
reg   [1:0] trunc_ln147_1_reg_584;
wire   [31:0] acc_fu_465_p11;
reg   [31:0] acc_reg_589;
reg   [5:0] A_address0;
reg    A_ce0;
reg    A_we0;
wire   [15:0] A_q0;
reg   [5:0] A_1_address0;
reg    A_1_ce0;
reg    A_1_we0;
wire   [15:0] A_1_q0;
reg   [5:0] A_2_address0;
reg    A_2_ce0;
reg    A_2_we0;
wire   [15:0] A_2_q0;
reg   [5:0] A_3_address0;
reg    A_3_ce0;
reg    A_3_we0;
wire   [15:0] A_3_q0;
reg   [5:0] B_address0;
reg    B_ce0;
reg    B_we0;
wire   [15:0] B_q0;
reg   [5:0] B_1_address0;
reg    B_1_ce0;
reg    B_1_we0;
wire   [15:0] B_1_q0;
reg   [5:0] B_2_address0;
reg    B_2_ce0;
reg    B_2_we0;
wire   [15:0] B_2_q0;
reg   [5:0] B_3_address0;
reg    B_3_ce0;
reg    B_3_we0;
wire   [15:0] B_3_q0;
reg   [5:0] C_address0;
reg    C_ce0;
reg    C_we0;
reg   [31:0] C_d0;
wire   [31:0] C_q0;
reg   [5:0] C_1_address0;
reg    C_1_ce0;
reg    C_1_we0;
reg   [31:0] C_1_d0;
wire   [31:0] C_1_q0;
reg   [5:0] C_2_address0;
reg    C_2_ce0;
reg    C_2_we0;
reg   [31:0] C_2_d0;
wire   [31:0] C_2_q0;
reg   [5:0] C_3_address0;
reg    C_3_ce0;
reg    C_3_we0;
reg   [31:0] C_3_d0;
wire   [31:0] C_3_q0;
wire    grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_ap_start;
wire    grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_ap_done;
wire    grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_ap_idle;
wire    grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_ap_ready;
wire   [5:0] grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_address0;
wire    grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_ce0;
wire    grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_we0;
wire   [31:0] grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_d0;
wire   [5:0] grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_1_address0;
wire    grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_1_ce0;
wire    grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_1_we0;
wire   [31:0] grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_1_d0;
wire   [5:0] grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_2_address0;
wire    grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_2_ce0;
wire    grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_2_we0;
wire   [31:0] grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_2_d0;
wire   [5:0] grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_3_address0;
wire    grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_3_ce0;
wire    grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_3_we0;
wire   [31:0] grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_3_d0;
wire    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_ap_start;
wire    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_ap_done;
wire    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_ap_idle;
wire    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_ap_ready;
wire   [5:0] grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_address0;
wire    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_ce0;
wire    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_we0;
wire   [15:0] grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_d0;
wire   [5:0] grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_1_address0;
wire    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_1_ce0;
wire    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_1_we0;
wire   [15:0] grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_1_d0;
wire   [5:0] grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_2_address0;
wire    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_2_ce0;
wire    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_2_we0;
wire   [15:0] grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_2_d0;
wire   [5:0] grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_3_address0;
wire    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_3_ce0;
wire    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_3_we0;
wire   [15:0] grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_3_d0;
wire    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_in_stream_TREADY;
wire    grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_ap_start;
wire    grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_ap_done;
wire    grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_ap_idle;
wire    grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_ap_ready;
wire    grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TREADY;
wire   [5:0] grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_C_address0;
wire    grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_C_ce0;
wire   [5:0] grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_C_1_address0;
wire    grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_C_1_ce0;
wire   [5:0] grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_C_2_address0;
wire    grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_C_2_ce0;
wire   [5:0] grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_C_3_address0;
wire    grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_C_3_ce0;
wire   [31:0] grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TDATA;
wire    grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TVALID;
wire   [3:0] grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TKEEP;
wire   [3:0] grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TSTRB;
wire   [0:0] grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TLAST;
wire    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_ap_start;
wire    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_ap_done;
wire    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_ap_idle;
wire    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_ap_ready;
wire   [5:0] grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_address0;
wire    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_ce0;
wire    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_we0;
wire   [15:0] grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_d0;
wire   [5:0] grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_1_address0;
wire    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_1_ce0;
wire    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_1_we0;
wire   [15:0] grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_1_d0;
wire   [5:0] grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_2_address0;
wire    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_2_ce0;
wire    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_2_we0;
wire   [15:0] grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_2_d0;
wire   [5:0] grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_3_address0;
wire    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_3_ce0;
wire    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_3_we0;
wire   [15:0] grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_3_d0;
wire    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_in_stream_TREADY;
wire    grp_stream_matmul_Pipeline_compute_k_fu_317_ap_start;
wire    grp_stream_matmul_Pipeline_compute_k_fu_317_ap_done;
wire    grp_stream_matmul_Pipeline_compute_k_fu_317_ap_idle;
wire    grp_stream_matmul_Pipeline_compute_k_fu_317_ap_ready;
wire   [5:0] grp_stream_matmul_Pipeline_compute_k_fu_317_A_address0;
wire    grp_stream_matmul_Pipeline_compute_k_fu_317_A_ce0;
wire   [5:0] grp_stream_matmul_Pipeline_compute_k_fu_317_A_1_address0;
wire    grp_stream_matmul_Pipeline_compute_k_fu_317_A_1_ce0;
wire   [5:0] grp_stream_matmul_Pipeline_compute_k_fu_317_A_2_address0;
wire    grp_stream_matmul_Pipeline_compute_k_fu_317_A_2_ce0;
wire   [5:0] grp_stream_matmul_Pipeline_compute_k_fu_317_A_3_address0;
wire    grp_stream_matmul_Pipeline_compute_k_fu_317_A_3_ce0;
wire   [5:0] grp_stream_matmul_Pipeline_compute_k_fu_317_B_address0;
wire    grp_stream_matmul_Pipeline_compute_k_fu_317_B_ce0;
wire   [5:0] grp_stream_matmul_Pipeline_compute_k_fu_317_B_1_address0;
wire    grp_stream_matmul_Pipeline_compute_k_fu_317_B_1_ce0;
wire   [5:0] grp_stream_matmul_Pipeline_compute_k_fu_317_B_2_address0;
wire    grp_stream_matmul_Pipeline_compute_k_fu_317_B_2_ce0;
wire   [5:0] grp_stream_matmul_Pipeline_compute_k_fu_317_B_3_address0;
wire    grp_stream_matmul_Pipeline_compute_k_fu_317_B_3_ce0;
wire   [31:0] grp_stream_matmul_Pipeline_compute_k_fu_317_acc_1_out;
wire    grp_stream_matmul_Pipeline_compute_k_fu_317_acc_1_out_ap_vld;
reg   [4:0] i_reg_234;
wire   [0:0] icmp_ln147_fu_420_p2;
wire    ap_CS_fsm_state6;
reg   [4:0] j_reg_245;
wire   [0:0] icmp_ln145_fu_400_p2;
wire    ap_CS_fsm_state12;
reg    grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_ap_start_reg;
wire    C_we0_out;
wire    C_1_we0_out;
wire    C_2_we0_out;
wire    C_3_we0_out;
reg    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_ap_start_reg;
wire   [0:0] icmp_ln112_fu_389_p2;
wire    ap_CS_fsm_state4;
reg    grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_ap_start_reg;
wire    ap_CS_fsm_state13;
reg   [31:0] out_stream_TDATA_reg;
reg   [3:0] out_stream_TKEEP_reg;
reg   [3:0] out_stream_TSTRB_reg;
reg   [0:0] out_stream_TLAST_reg;
reg    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_stream_matmul_Pipeline_compute_k_fu_317_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire   [63:0] zext_ln148_fu_449_p1;
reg   [31:0] kk_fu_124;
reg    C_ce0_local;
reg   [5:0] C_address0_local;
reg    C_we0_local;
reg    C_1_ce0_local;
reg   [5:0] C_1_address0_local;
reg    C_1_we0_local;
reg    C_2_ce0_local;
reg   [5:0] C_2_address0_local;
reg    C_2_we0_local;
reg    C_3_ce0_local;
reg   [5:0] C_3_address0_local;
reg    C_3_we0_local;
wire   [30:0] tmp_fu_333_p4;
wire   [0:0] icmp_fu_343_p2;
wire   [31:0] xor_ln112_fu_349_p2;
wire   [0:0] empty_fu_368_p2;
wire   [31:0] xor_ln112_1_fu_373_p2;
wire   [1:0] lshr_ln84_3_fu_432_p4;
wire   [5:0] tmp_s_fu_442_p3;
wire   [31:0] acc_fu_465_p9;
wire   [1:0] acc_fu_465_p10;
wire    ap_CS_fsm_state14;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
reg   [13:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [31:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [3:0] in_stream_TKEEP_int_regslice;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [3:0] in_stream_TSTRB_int_regslice;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int_regslice;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
reg   [31:0] out_stream_TDATA_int_regslice;
wire    out_stream_TVALID_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
reg   [3:0] out_stream_TKEEP_int_regslice;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
reg   [3:0] out_stream_TSTRB_int_regslice;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
reg   [0:0] out_stream_TLAST_int_regslice;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;
wire   [1:0] acc_fu_465_p1;
wire   [1:0] acc_fu_465_p3;
wire  signed [1:0] acc_fu_465_p5;
wire  signed [1:0] acc_fu_465_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
#0 grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_ap_start_reg = 1'b0;
#0 grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_ap_start_reg = 1'b0;
#0 grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_ap_start_reg = 1'b0;
#0 grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_ap_start_reg = 1'b0;
#0 grp_stream_matmul_Pipeline_compute_k_fu_317_ap_start_reg = 1'b0;
#0 kk_fu_124 = 32'd0;
end

stream_matmul_A_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_address0),
    .ce0(A_ce0),
    .we0(A_we0),
    .d0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_d0),
    .q0(A_q0)
);

stream_matmul_A_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_1_address0),
    .ce0(A_1_ce0),
    .we0(A_1_we0),
    .d0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_1_d0),
    .q0(A_1_q0)
);

stream_matmul_A_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_2_address0),
    .ce0(A_2_ce0),
    .we0(A_2_we0),
    .d0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_2_d0),
    .q0(A_2_q0)
);

stream_matmul_A_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_3_address0),
    .ce0(A_3_ce0),
    .we0(A_3_we0),
    .d0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_3_d0),
    .q0(A_3_q0)
);

stream_matmul_A_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
B_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(B_address0),
    .ce0(B_ce0),
    .we0(B_we0),
    .d0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_d0),
    .q0(B_q0)
);

stream_matmul_A_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
B_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(B_1_address0),
    .ce0(B_1_ce0),
    .we0(B_1_we0),
    .d0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_1_d0),
    .q0(B_1_q0)
);

stream_matmul_A_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
B_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(B_2_address0),
    .ce0(B_2_ce0),
    .we0(B_2_we0),
    .d0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_2_d0),
    .q0(B_2_q0)
);

stream_matmul_A_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
B_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(B_3_address0),
    .ce0(B_3_ce0),
    .we0(B_3_we0),
    .d0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_3_d0),
    .q0(B_3_q0)
);

stream_matmul_C_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
C_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(C_address0),
    .ce0(C_ce0),
    .we0(C_we0),
    .d0(C_d0),
    .q0(C_q0)
);

stream_matmul_C_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
C_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(C_1_address0),
    .ce0(C_1_ce0),
    .we0(C_1_we0),
    .d0(C_1_d0),
    .q0(C_1_q0)
);

stream_matmul_C_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
C_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(C_2_address0),
    .ce0(C_2_ce0),
    .we0(C_2_we0),
    .d0(C_2_d0),
    .q0(C_2_q0)
);

stream_matmul_C_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
C_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(C_3_address0),
    .ce0(C_3_ce0),
    .we0(C_3_we0),
    .d0(C_3_d0),
    .q0(C_3_q0)
);

stream_matmul_stream_matmul_Pipeline_init_c_i_init_c_j grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_ap_start),
    .ap_done(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_ap_done),
    .ap_idle(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_ap_idle),
    .ap_ready(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_ap_ready),
    .C_address0(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_address0),
    .C_ce0(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_ce0),
    .C_we0(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_we0),
    .C_d0(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_d0),
    .C_1_address0(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_1_address0),
    .C_1_ce0(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_1_ce0),
    .C_1_we0(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_1_we0),
    .C_1_d0(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_1_d0),
    .C_2_address0(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_2_address0),
    .C_2_ce0(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_2_ce0),
    .C_2_we0(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_2_we0),
    .C_2_d0(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_2_d0),
    .C_3_address0(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_3_address0),
    .C_3_ce0(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_3_ce0),
    .C_3_we0(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_3_we0),
    .C_3_d0(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_3_d0)
);

stream_matmul_stream_matmul_Pipeline_read_a_i_read_a_j grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_ap_start),
    .ap_done(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_ap_done),
    .ap_idle(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_ap_idle),
    .ap_ready(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_ap_ready),
    .in_stream_TVALID(in_stream_TVALID_int_regslice),
    .A_address0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_address0),
    .A_ce0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_ce0),
    .A_we0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_we0),
    .A_d0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_d0),
    .A_1_address0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_1_address0),
    .A_1_ce0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_1_ce0),
    .A_1_we0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_1_we0),
    .A_1_d0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_1_d0),
    .A_2_address0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_2_address0),
    .A_2_ce0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_2_ce0),
    .A_2_we0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_2_we0),
    .A_2_d0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_2_d0),
    .A_3_address0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_3_address0),
    .A_3_ce0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_3_ce0),
    .A_3_we0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_3_we0),
    .A_3_d0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_3_d0),
    .in_stream_TDATA(in_stream_TDATA_int_regslice),
    .in_stream_TREADY(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_in_stream_TREADY),
    .in_stream_TKEEP(in_stream_TKEEP_int_regslice),
    .in_stream_TSTRB(in_stream_TSTRB_int_regslice),
    .in_stream_TLAST(in_stream_TLAST_int_regslice)
);

stream_matmul_stream_matmul_Pipeline_write_c_i_write_c_j grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_ap_start),
    .ap_done(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_ap_done),
    .ap_idle(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_ap_idle),
    .ap_ready(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_ap_ready),
    .out_stream_TREADY(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TREADY),
    .C_address0(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_C_address0),
    .C_ce0(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_C_ce0),
    .C_q0(C_q0),
    .C_1_address0(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_C_1_address0),
    .C_1_ce0(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_C_1_ce0),
    .C_1_q0(C_1_q0),
    .C_2_address0(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_C_2_address0),
    .C_2_ce0(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_C_2_ce0),
    .C_2_q0(C_2_q0),
    .C_3_address0(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_C_3_address0),
    .C_3_ce0(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_C_3_ce0),
    .C_3_q0(C_3_q0),
    .out_stream_TDATA(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TDATA),
    .out_stream_TVALID(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TVALID),
    .out_stream_TKEEP(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TKEEP),
    .out_stream_TSTRB(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TSTRB),
    .out_stream_TLAST(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TLAST)
);

stream_matmul_stream_matmul_Pipeline_read_b_i_read_b_j grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_ap_start),
    .ap_done(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_ap_done),
    .ap_idle(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_ap_idle),
    .ap_ready(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_ap_ready),
    .in_stream_TVALID(in_stream_TVALID_int_regslice),
    .B_address0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_address0),
    .B_ce0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_ce0),
    .B_we0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_we0),
    .B_d0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_d0),
    .B_1_address0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_1_address0),
    .B_1_ce0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_1_ce0),
    .B_1_we0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_1_we0),
    .B_1_d0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_1_d0),
    .B_2_address0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_2_address0),
    .B_2_ce0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_2_ce0),
    .B_2_we0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_2_we0),
    .B_2_d0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_2_d0),
    .B_3_address0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_3_address0),
    .B_3_ce0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_3_ce0),
    .B_3_we0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_3_we0),
    .B_3_d0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_3_d0),
    .in_stream_TDATA(in_stream_TDATA_int_regslice),
    .in_stream_TREADY(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_in_stream_TREADY),
    .in_stream_TKEEP(in_stream_TKEEP_int_regslice),
    .in_stream_TSTRB(in_stream_TSTRB_int_regslice),
    .in_stream_TLAST(in_stream_TLAST_int_regslice)
);

stream_matmul_stream_matmul_Pipeline_compute_k grp_stream_matmul_Pipeline_compute_k_fu_317(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_stream_matmul_Pipeline_compute_k_fu_317_ap_start),
    .ap_done(grp_stream_matmul_Pipeline_compute_k_fu_317_ap_done),
    .ap_idle(grp_stream_matmul_Pipeline_compute_k_fu_317_ap_idle),
    .ap_ready(grp_stream_matmul_Pipeline_compute_k_fu_317_ap_ready),
    .acc(acc_reg_589),
    .i_4(trunc_ln145_reg_545),
    .A_address0(grp_stream_matmul_Pipeline_compute_k_fu_317_A_address0),
    .A_ce0(grp_stream_matmul_Pipeline_compute_k_fu_317_A_ce0),
    .A_q0(A_q0),
    .A_1_address0(grp_stream_matmul_Pipeline_compute_k_fu_317_A_1_address0),
    .A_1_ce0(grp_stream_matmul_Pipeline_compute_k_fu_317_A_1_ce0),
    .A_1_q0(A_1_q0),
    .A_2_address0(grp_stream_matmul_Pipeline_compute_k_fu_317_A_2_address0),
    .A_2_ce0(grp_stream_matmul_Pipeline_compute_k_fu_317_A_2_ce0),
    .A_2_q0(A_2_q0),
    .A_3_address0(grp_stream_matmul_Pipeline_compute_k_fu_317_A_3_address0),
    .A_3_ce0(grp_stream_matmul_Pipeline_compute_k_fu_317_A_3_ce0),
    .A_3_q0(A_3_q0),
    .zext_ln147(trunc_ln147_reg_579),
    .B_address0(grp_stream_matmul_Pipeline_compute_k_fu_317_B_address0),
    .B_ce0(grp_stream_matmul_Pipeline_compute_k_fu_317_B_ce0),
    .B_q0(B_q0),
    .B_1_address0(grp_stream_matmul_Pipeline_compute_k_fu_317_B_1_address0),
    .B_1_ce0(grp_stream_matmul_Pipeline_compute_k_fu_317_B_1_ce0),
    .B_1_q0(B_1_q0),
    .B_2_address0(grp_stream_matmul_Pipeline_compute_k_fu_317_B_2_address0),
    .B_2_ce0(grp_stream_matmul_Pipeline_compute_k_fu_317_B_2_ce0),
    .B_2_q0(B_2_q0),
    .B_3_address0(grp_stream_matmul_Pipeline_compute_k_fu_317_B_3_address0),
    .B_3_ce0(grp_stream_matmul_Pipeline_compute_k_fu_317_B_3_ce0),
    .B_3_q0(B_3_q0),
    .acc_1_out(grp_stream_matmul_Pipeline_compute_k_fu_317_acc_1_out),
    .acc_1_out_ap_vld(grp_stream_matmul_Pipeline_compute_k_fu_317_acc_1_out_ap_vld)
);

stream_matmul_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .num_k_tiles(num_k_tiles),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

(* dissolve_hierarchy = "yes" *) stream_matmul_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U48(
    .din0(C_q0),
    .din1(C_1_q0),
    .din2(C_2_q0),
    .din3(C_3_q0),
    .def(acc_fu_465_p9),
    .sel(acc_fu_465_p10),
    .dout(acc_fu_465_p11)
);

stream_matmul_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

stream_matmul_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

stream_matmul_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

stream_matmul_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int_regslice),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

stream_matmul_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TDATA_int_regslice),
    .vld_in(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TVALID),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

stream_matmul_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TKEEP_int_regslice),
    .vld_in(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

stream_matmul_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TSTRB_int_regslice),
    .vld_in(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

stream_matmul_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TLAST_int_regslice),
    .vld_in(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_stream_matmul_Pipeline_compute_k_fu_317_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_stream_matmul_Pipeline_compute_k_fu_317_ap_start_reg <= 1'b1;
        end else if ((grp_stream_matmul_Pipeline_compute_k_fu_317_ap_ready == 1'b1)) begin
            grp_stream_matmul_Pipeline_compute_k_fu_317_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_ap_start_reg <= 1'b1;
        end else if ((grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_ap_ready == 1'b1)) begin
            grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln112_fu_389_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_ap_start_reg <= 1'b1;
        end else if ((grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_ap_ready == 1'b1)) begin
            grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_ap_start_reg <= 1'b1;
        end else if ((grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_ap_ready == 1'b1)) begin
            grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln112_fu_389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_ap_start_reg <= 1'b1;
        end else if ((grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_ap_ready == 1'b1)) begin
            grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        i_reg_234 <= 5'd0;
    end else if (((icmp_ln147_fu_420_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        i_reg_234 <= add_ln145_reg_540;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        j_reg_245 <= add_ln147_reg_554;
    end else if (((icmp_ln145_fu_400_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        j_reg_245 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kk_fu_124 <= 32'd0;
    end else if (((icmp_ln145_fu_400_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        kk_fu_124 <= add_ln112_reg_532;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        C_1_addr_reg_564 <= zext_ln148_fu_449_p1;
        C_2_addr_reg_569 <= zext_ln148_fu_449_p1;
        C_3_addr_reg_574 <= zext_ln148_fu_449_p1;
        C_addr_reg_559 <= zext_ln148_fu_449_p1;
        add_ln147_reg_554 <= add_ln147_fu_426_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        acc_reg_589 <= acc_fu_465_p11;
        trunc_ln147_1_reg_584 <= trunc_ln147_1_fu_461_p1;
        trunc_ln147_reg_579 <= trunc_ln147_fu_457_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln112_reg_532 <= add_ln112_fu_394_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln145_reg_540 <= add_ln145_fu_406_p2;
        trunc_ln145_reg_545 <= trunc_ln145_fu_412_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        out_stream_TDATA_reg <= grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TDATA;
        out_stream_TKEEP_reg <= grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TKEEP;
        out_stream_TLAST_reg <= grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TLAST;
        out_stream_TSTRB_reg <= grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TSTRB;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        select_ln112_1_reg_524 <= select_ln112_1_fu_378_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        select_ln112_reg_518 <= select_ln112_fu_355_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_1_address0 = grp_stream_matmul_Pipeline_compute_k_fu_317_A_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        A_1_address0 = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_1_address0;
    end else begin
        A_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_1_ce0 = grp_stream_matmul_Pipeline_compute_k_fu_317_A_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        A_1_ce0 = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_1_ce0;
    end else begin
        A_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_1_we0 = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_1_we0;
    end else begin
        A_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_2_address0 = grp_stream_matmul_Pipeline_compute_k_fu_317_A_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        A_2_address0 = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_2_address0;
    end else begin
        A_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_2_ce0 = grp_stream_matmul_Pipeline_compute_k_fu_317_A_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        A_2_ce0 = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_2_ce0;
    end else begin
        A_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_2_we0 = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_2_we0;
    end else begin
        A_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_3_address0 = grp_stream_matmul_Pipeline_compute_k_fu_317_A_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        A_3_address0 = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_3_address0;
    end else begin
        A_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_3_ce0 = grp_stream_matmul_Pipeline_compute_k_fu_317_A_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        A_3_ce0 = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_3_ce0;
    end else begin
        A_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_3_we0 = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_3_we0;
    end else begin
        A_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_address0 = grp_stream_matmul_Pipeline_compute_k_fu_317_A_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        A_address0 = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_address0;
    end else begin
        A_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_ce0 = grp_stream_matmul_Pipeline_compute_k_fu_317_A_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        A_ce0 = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_ce0;
    end else begin
        A_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_we0 = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_A_we0;
    end else begin
        A_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        B_1_address0 = grp_stream_matmul_Pipeline_compute_k_fu_317_B_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_1_address0 = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_1_address0;
    end else begin
        B_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        B_1_ce0 = grp_stream_matmul_Pipeline_compute_k_fu_317_B_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_1_ce0 = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_1_ce0;
    end else begin
        B_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        B_1_we0 = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_1_we0;
    end else begin
        B_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        B_2_address0 = grp_stream_matmul_Pipeline_compute_k_fu_317_B_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_2_address0 = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_2_address0;
    end else begin
        B_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        B_2_ce0 = grp_stream_matmul_Pipeline_compute_k_fu_317_B_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_2_ce0 = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_2_ce0;
    end else begin
        B_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        B_2_we0 = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_2_we0;
    end else begin
        B_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        B_3_address0 = grp_stream_matmul_Pipeline_compute_k_fu_317_B_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_3_address0 = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_3_address0;
    end else begin
        B_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        B_3_ce0 = grp_stream_matmul_Pipeline_compute_k_fu_317_B_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_3_ce0 = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_3_ce0;
    end else begin
        B_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        B_3_we0 = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_3_we0;
    end else begin
        B_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        B_address0 = grp_stream_matmul_Pipeline_compute_k_fu_317_B_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_address0 = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_address0;
    end else begin
        B_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        B_ce0 = grp_stream_matmul_Pipeline_compute_k_fu_317_B_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_ce0 = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_ce0;
    end else begin
        B_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        B_we0 = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_B_we0;
    end else begin
        B_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        C_1_address0 = grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_C_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        C_1_address0 = grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_1_address0;
    end else begin
        C_1_address0 = C_1_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        C_1_address0_local = C_1_addr_reg_564;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        C_1_address0_local = zext_ln148_fu_449_p1;
    end else begin
        C_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        C_1_ce0 = grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_C_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        C_1_ce0 = grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_1_ce0;
    end else begin
        C_1_ce0 = C_1_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state12))) begin
        C_1_ce0_local = 1'b1;
    end else begin
        C_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        C_1_d0 = grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_1_d0;
    end else begin
        C_1_d0 = grp_stream_matmul_Pipeline_compute_k_fu_317_acc_1_out;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        C_1_we0 = grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_1_we0;
    end else begin
        C_1_we0 = (1'b0 | C_1_we0_out);
    end
end

always @ (*) begin
    if (((trunc_ln147_1_reg_584 == 2'd1) & (1'b1 == ap_CS_fsm_state12))) begin
        C_1_we0_local = 1'b1;
    end else begin
        C_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        C_2_address0 = grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_C_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        C_2_address0 = grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_2_address0;
    end else begin
        C_2_address0 = C_2_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        C_2_address0_local = C_2_addr_reg_569;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        C_2_address0_local = zext_ln148_fu_449_p1;
    end else begin
        C_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        C_2_ce0 = grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_C_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        C_2_ce0 = grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_2_ce0;
    end else begin
        C_2_ce0 = C_2_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state12))) begin
        C_2_ce0_local = 1'b1;
    end else begin
        C_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        C_2_d0 = grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_2_d0;
    end else begin
        C_2_d0 = grp_stream_matmul_Pipeline_compute_k_fu_317_acc_1_out;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        C_2_we0 = grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_2_we0;
    end else begin
        C_2_we0 = (1'b0 | C_2_we0_out);
    end
end

always @ (*) begin
    if (((trunc_ln147_1_reg_584 == 2'd2) & (1'b1 == ap_CS_fsm_state12))) begin
        C_2_we0_local = 1'b1;
    end else begin
        C_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        C_3_address0 = grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_C_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        C_3_address0 = grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_3_address0;
    end else begin
        C_3_address0 = C_3_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        C_3_address0_local = C_3_addr_reg_574;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        C_3_address0_local = zext_ln148_fu_449_p1;
    end else begin
        C_3_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        C_3_ce0 = grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_C_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        C_3_ce0 = grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_3_ce0;
    end else begin
        C_3_ce0 = C_3_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state12))) begin
        C_3_ce0_local = 1'b1;
    end else begin
        C_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        C_3_d0 = grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_3_d0;
    end else begin
        C_3_d0 = grp_stream_matmul_Pipeline_compute_k_fu_317_acc_1_out;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        C_3_we0 = grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_3_we0;
    end else begin
        C_3_we0 = (1'b0 | C_3_we0_out);
    end
end

always @ (*) begin
    if (((trunc_ln147_1_reg_584 == 2'd3) & (1'b1 == ap_CS_fsm_state12))) begin
        C_3_we0_local = 1'b1;
    end else begin
        C_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        C_address0 = grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_C_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        C_address0 = grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_address0;
    end else begin
        C_address0 = C_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        C_address0_local = C_addr_reg_559;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        C_address0_local = zext_ln148_fu_449_p1;
    end else begin
        C_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        C_ce0 = grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_C_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        C_ce0 = grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_ce0;
    end else begin
        C_ce0 = C_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state12))) begin
        C_ce0_local = 1'b1;
    end else begin
        C_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        C_d0 = grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_d0;
    end else begin
        C_d0 = grp_stream_matmul_Pipeline_compute_k_fu_317_acc_1_out;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        C_we0 = grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_C_we0;
    end else begin
        C_we0 = (1'b0 | C_we0_out);
    end
end

always @ (*) begin
    if (((trunc_ln147_1_reg_584 == 2'd0) & (1'b1 == ap_CS_fsm_state12))) begin
        C_we0_local = 1'b1;
    end else begin
        C_we0_local = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_stream_matmul_Pipeline_compute_k_fu_317_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        in_stream_TREADY_int_regslice = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_in_stream_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        in_stream_TREADY_int_regslice = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_in_stream_TREADY;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        out_stream_TDATA_int_regslice = grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TDATA;
    end else begin
        out_stream_TDATA_int_regslice = out_stream_TDATA_reg;
    end
end

always @ (*) begin
    if (((grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        out_stream_TKEEP_int_regslice = grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TKEEP;
    end else begin
        out_stream_TKEEP_int_regslice = out_stream_TKEEP_reg;
    end
end

always @ (*) begin
    if (((grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        out_stream_TLAST_int_regslice = grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TLAST;
    end else begin
        out_stream_TLAST_int_regslice = out_stream_TLAST_reg;
    end
end

always @ (*) begin
    if (((grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        out_stream_TSTRB_int_regslice = grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TSTRB;
    end else begin
        out_stream_TSTRB_int_regslice = out_stream_TSTRB_reg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln112_fu_389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((icmp_ln145_fu_400_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((icmp_ln147_fu_420_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_stream_matmul_Pipeline_compute_k_fu_317_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state13 : begin
            if (((grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C_1_we0_out = C_1_we0_local;

assign C_2_we0_out = C_2_we0_local;

assign C_3_we0_out = C_3_we0_local;

assign C_we0_out = C_we0_local;

assign acc_fu_465_p10 = j_reg_245[1:0];

assign acc_fu_465_p9 = 'bx;

assign add_ln112_fu_394_p2 = (kk_fu_124 + 32'd1);

assign add_ln145_fu_406_p2 = (i_reg_234 + 5'd1);

assign add_ln147_fu_426_p2 = (j_reg_245 + 5'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign empty_fu_368_p2 = (($signed(select_ln112_reg_518) > $signed(32'd4294967231)) ? 1'b1 : 1'b0);

assign grp_stream_matmul_Pipeline_compute_k_fu_317_ap_start = grp_stream_matmul_Pipeline_compute_k_fu_317_ap_start_reg;

assign grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_ap_start = grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_257_ap_start_reg;

assign grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_ap_start = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_269_ap_start_reg;

assign grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_ap_start = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_301_ap_start_reg;

assign grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_ap_start = grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_ap_start_reg;

assign grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TREADY = (out_stream_TREADY_int_regslice & ap_CS_fsm_state13);

assign icmp_fu_343_p2 = (($signed(tmp_fu_333_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln112_fu_389_p2 = ((kk_fu_124 == select_ln112_1_reg_524) ? 1'b1 : 1'b0);

assign icmp_ln145_fu_400_p2 = ((i_reg_234 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln147_fu_420_p2 = ((j_reg_245 == 5'd16) ? 1'b1 : 1'b0);

assign in_stream_TREADY = regslice_both_in_stream_V_data_V_U_ack_in;

assign lshr_ln84_3_fu_432_p4 = {{j_reg_245[3:2]}};

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign out_stream_TVALID_int_regslice = grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_285_out_stream_TVALID;

assign select_ln112_1_fu_378_p3 = ((empty_fu_368_p2[0:0] == 1'b1) ? xor_ln112_1_fu_373_p2 : 32'd64);

assign select_ln112_fu_355_p3 = ((icmp_fu_343_p2[0:0] == 1'b1) ? xor_ln112_fu_349_p2 : 32'd4294967294);

assign tmp_fu_333_p4 = {{num_k_tiles[31:1]}};

assign tmp_s_fu_442_p3 = {{trunc_ln145_reg_545}, {lshr_ln84_3_fu_432_p4}};

assign trunc_ln145_fu_412_p1 = i_reg_234[3:0];

assign trunc_ln147_1_fu_461_p1 = j_reg_245[1:0];

assign trunc_ln147_fu_457_p1 = j_reg_245[3:0];

assign xor_ln112_1_fu_373_p2 = (select_ln112_reg_518 ^ 32'd4294967295);

assign xor_ln112_fu_349_p2 = (num_k_tiles ^ 32'd4294967295);

assign zext_ln148_fu_449_p1 = tmp_s_fu_442_p3;


reg find_kernel_block = 0;
// synthesis translate_off
`include "stream_matmul_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //stream_matmul

