// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module stream_matmul_stream_matmul_Pipeline_init_c_i_init_c_j (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        C_address0,
        C_ce0,
        C_we0,
        C_d0,
        C_1_address0,
        C_1_ce0,
        C_1_we0,
        C_1_d0,
        C_2_address0,
        C_2_ce0,
        C_2_we0,
        C_2_d0,
        C_3_address0,
        C_3_ce0,
        C_3_we0,
        C_3_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] C_address0;
output   C_ce0;
output   C_we0;
output  [31:0] C_d0;
output  [5:0] C_1_address0;
output   C_1_ce0;
output   C_1_we0;
output  [31:0] C_1_d0;
output  [5:0] C_2_address0;
output   C_2_ce0;
output   C_2_we0;
output  [31:0] C_2_d0;
output  [5:0] C_3_address0;
output   C_3_ce0;
output   C_3_we0;
output  [31:0] C_3_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln100_fu_140_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln102_fu_160_p2;
reg   [0:0] icmp_ln102_reg_274;
wire   [1:0] trunc_ln102_1_fu_174_p1;
reg   [1:0] trunc_ln102_1_reg_279;
reg   [1:0] lshr_ln_reg_283;
wire   [63:0] zext_ln104_fu_236_p1;
wire    ap_block_pp0_stage0;
reg   [4:0] j_fu_54;
wire   [4:0] add_ln102_fu_198_p2;
wire    ap_loop_init;
reg   [4:0] i_fu_58;
wire   [4:0] select_ln100_fu_218_p3;
reg   [8:0] indvar_flatten_fu_62;
wire   [8:0] add_ln100_1_fu_146_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten_load;
reg    C_2_we0_local;
reg    C_2_ce0_local;
reg    C_1_we0_local;
reg    C_1_ce0_local;
reg    C_we0_local;
reg    C_ce0_local;
reg    C_3_we0_local;
reg    C_3_ce0_local;
wire   [4:0] select_ln84_fu_166_p3;
wire   [4:0] add_ln100_fu_212_p2;
wire   [3:0] trunc_ln102_fu_225_p1;
wire   [5:0] tmp_s_fu_229_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 j_fu_54 = 5'd0;
#0 i_fu_58 = 5'd0;
#0 indvar_flatten_fu_62 = 9'd0;
#0 ap_done_reg = 1'b0;
end

stream_matmul_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            i_fu_58 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            i_fu_58 <= select_ln100_fu_218_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln100_fu_140_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_62 <= add_ln100_1_fu_146_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_62 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_54 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            j_fu_54 <= add_ln102_fu_198_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln102_reg_274 <= icmp_ln102_fu_160_p2;
        lshr_ln_reg_283 <= {{select_ln84_fu_166_p3[3:2]}};
        trunc_ln102_1_reg_279 <= trunc_ln102_1_fu_174_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        C_1_ce0_local = 1'b1;
    end else begin
        C_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln102_1_reg_279 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        C_1_we0_local = 1'b1;
    end else begin
        C_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        C_2_ce0_local = 1'b1;
    end else begin
        C_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln102_1_reg_279 == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        C_2_we0_local = 1'b1;
    end else begin
        C_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        C_3_ce0_local = 1'b1;
    end else begin
        C_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln102_1_reg_279 == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        C_3_we0_local = 1'b1;
    end else begin
        C_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        C_ce0_local = 1'b1;
    end else begin
        C_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln102_1_reg_279 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        C_we0_local = 1'b1;
    end else begin
        C_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln100_fu_140_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_62;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C_1_address0 = zext_ln104_fu_236_p1;

assign C_1_ce0 = C_1_ce0_local;

assign C_1_d0 = 32'd0;

assign C_1_we0 = C_1_we0_local;

assign C_2_address0 = zext_ln104_fu_236_p1;

assign C_2_ce0 = C_2_ce0_local;

assign C_2_d0 = 32'd0;

assign C_2_we0 = C_2_we0_local;

assign C_3_address0 = zext_ln104_fu_236_p1;

assign C_3_ce0 = C_3_ce0_local;

assign C_3_d0 = 32'd0;

assign C_3_we0 = C_3_we0_local;

assign C_address0 = zext_ln104_fu_236_p1;

assign C_ce0 = C_ce0_local;

assign C_d0 = 32'd0;

assign C_we0 = C_we0_local;

assign add_ln100_1_fu_146_p2 = (ap_sig_allocacmp_indvar_flatten_load + 9'd1);

assign add_ln100_fu_212_p2 = (i_fu_58 + 5'd1);

assign add_ln102_fu_198_p2 = (select_ln84_fu_166_p3 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln100_fu_140_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln102_fu_160_p2 = ((j_fu_54 == 5'd16) ? 1'b1 : 1'b0);

assign select_ln100_fu_218_p3 = ((icmp_ln102_reg_274[0:0] == 1'b1) ? add_ln100_fu_212_p2 : i_fu_58);

assign select_ln84_fu_166_p3 = ((icmp_ln102_fu_160_p2[0:0] == 1'b1) ? 5'd0 : j_fu_54);

assign tmp_s_fu_229_p3 = {{trunc_ln102_fu_225_p1}, {lshr_ln_reg_283}};

assign trunc_ln102_1_fu_174_p1 = select_ln84_fu_166_p3[1:0];

assign trunc_ln102_fu_225_p1 = select_ln100_fu_218_p3[3:0];

assign zext_ln104_fu_236_p1 = tmp_s_fu_229_p3;

endmodule //stream_matmul_stream_matmul_Pipeline_init_c_i_init_c_j
