// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="stream_matmul_stream_matmul,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.256000,HLS_SYN_LAT=705675,HLS_SYN_TPT=none,HLS_SYN_MEM=9,HLS_SYN_DSP=0,HLS_SYN_FF=1281,HLS_SYN_LUT=2701,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module stream_matmul (
        ap_clk,
        ap_rst_n,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] num_k_tiles;
wire   [31:0] select_ln99_fu_222_p3;
reg   [31:0] select_ln99_reg_279;
wire   [31:0] select_ln99_1_fu_245_p3;
reg   [31:0] select_ln99_1_reg_285;
wire    ap_CS_fsm_state2;
reg   [5:0] A_address0;
reg    A_ce0;
reg    A_we0;
wire   [31:0] A_q0;
reg   [5:0] A_1_address0;
reg    A_1_ce0;
reg    A_1_we0;
wire   [31:0] A_1_q0;
reg   [5:0] A_2_address0;
reg    A_2_ce0;
reg    A_2_we0;
wire   [31:0] A_2_q0;
reg   [5:0] A_3_address0;
reg    A_3_ce0;
reg    A_3_we0;
wire   [31:0] A_3_q0;
reg   [5:0] B_address0;
reg    B_ce0;
reg    B_we0;
wire   [31:0] B_q0;
reg   [5:0] B_1_address0;
reg    B_1_ce0;
reg    B_1_we0;
wire   [31:0] B_1_q0;
reg   [5:0] B_2_address0;
reg    B_2_ce0;
reg    B_2_we0;
wire   [31:0] B_2_q0;
reg   [5:0] B_3_address0;
reg    B_3_ce0;
reg    B_3_we0;
wire   [31:0] B_3_q0;
reg   [7:0] C_address0;
reg    C_ce0;
reg    C_we0;
reg   [31:0] C_d0;
wire   [31:0] C_q0;
wire    grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_ap_start;
wire    grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_ap_done;
wire    grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_ap_idle;
wire    grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_ap_ready;
wire   [7:0] grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_C_address0;
wire    grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_C_ce0;
wire    grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_C_we0;
wire   [31:0] grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_C_d0;
wire    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_ap_start;
wire    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_ap_done;
wire    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_ap_idle;
wire    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_ap_ready;
wire   [5:0] grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_address0;
wire    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_ce0;
wire    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_we0;
wire   [31:0] grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_d0;
wire   [5:0] grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_1_address0;
wire    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_1_ce0;
wire    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_1_we0;
wire   [31:0] grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_1_d0;
wire   [5:0] grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_2_address0;
wire    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_2_ce0;
wire    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_2_we0;
wire   [31:0] grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_2_d0;
wire   [5:0] grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_3_address0;
wire    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_3_ce0;
wire    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_3_we0;
wire   [31:0] grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_3_d0;
wire    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_in_stream_TREADY;
wire    grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_ap_start;
wire    grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_ap_done;
wire    grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_ap_idle;
wire    grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_ap_ready;
wire    grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TREADY;
wire   [7:0] grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_C_address0;
wire    grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_C_ce0;
wire   [31:0] grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TDATA;
wire    grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TVALID;
wire   [3:0] grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TKEEP;
wire   [3:0] grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TSTRB;
wire   [0:0] grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TLAST;
wire    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_ap_start;
wire    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_ap_done;
wire    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_ap_idle;
wire    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_ap_ready;
wire   [5:0] grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_address0;
wire    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_ce0;
wire    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_we0;
wire   [31:0] grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_d0;
wire   [5:0] grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_1_address0;
wire    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_1_ce0;
wire    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_1_we0;
wire   [31:0] grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_1_d0;
wire   [5:0] grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_2_address0;
wire    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_2_ce0;
wire    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_2_we0;
wire   [31:0] grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_2_d0;
wire   [5:0] grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_3_address0;
wire    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_3_ce0;
wire    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_3_we0;
wire   [31:0] grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_3_d0;
wire    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_in_stream_TREADY;
wire    grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_ap_start;
wire    grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_ap_done;
wire    grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_ap_idle;
wire    grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_ap_ready;
wire   [5:0] grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_A_address0;
wire    grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_A_ce0;
wire   [5:0] grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_A_1_address0;
wire    grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_A_1_ce0;
wire   [5:0] grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_A_2_address0;
wire    grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_A_2_ce0;
wire   [5:0] grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_A_3_address0;
wire    grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_A_3_ce0;
wire   [5:0] grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_B_address0;
wire    grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_B_ce0;
wire   [5:0] grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_B_1_address0;
wire    grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_B_1_ce0;
wire   [5:0] grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_B_2_address0;
wire    grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_B_2_ce0;
wire   [5:0] grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_B_3_address0;
wire    grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_B_3_ce0;
wire   [7:0] grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_C_address0;
wire    grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_C_ce0;
wire    grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_C_we0;
wire   [31:0] grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_C_d0;
reg    grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_ap_start_reg;
reg    grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_ap_start_reg;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln99_fu_256_p2;
wire    ap_CS_fsm_state4;
reg    grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_ap_start_reg;
wire    ap_CS_fsm_state9;
reg   [31:0] out_stream_TDATA_reg;
reg   [3:0] out_stream_TKEEP_reg;
reg   [3:0] out_stream_TSTRB_reg;
reg   [0:0] out_stream_TLAST_reg;
reg    grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_ap_start_reg;
reg   [9:0] ap_NS_fsm;
wire    ap_NS_fsm_state7;
wire    ap_CS_fsm_state8;
reg   [31:0] kk_fu_90;
wire   [31:0] add_ln99_fu_261_p2;
wire   [30:0] tmp_fu_200_p4;
wire   [0:0] icmp_fu_210_p2;
wire   [31:0] xor_ln99_fu_216_p2;
wire   [0:0] empty_fu_235_p2;
wire   [31:0] xor_ln99_1_fu_240_p2;
wire    ap_CS_fsm_state10;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [31:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [3:0] in_stream_TKEEP_int_regslice;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [3:0] in_stream_TSTRB_int_regslice;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int_regslice;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
reg   [31:0] out_stream_TDATA_int_regslice;
wire    out_stream_TVALID_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
reg   [3:0] out_stream_TKEEP_int_regslice;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
reg   [3:0] out_stream_TSTRB_int_regslice;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
reg   [0:0] out_stream_TLAST_int_regslice;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_ap_start_reg = 1'b0;
#0 grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_ap_start_reg = 1'b0;
#0 grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_ap_start_reg = 1'b0;
#0 grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_ap_start_reg = 1'b0;
#0 grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_ap_start_reg = 1'b0;
#0 kk_fu_90 = 32'd0;
end

stream_matmul_A_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_address0),
    .ce0(A_ce0),
    .we0(A_we0),
    .d0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_d0),
    .q0(A_q0)
);

stream_matmul_A_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_1_address0),
    .ce0(A_1_ce0),
    .we0(A_1_we0),
    .d0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_1_d0),
    .q0(A_1_q0)
);

stream_matmul_A_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_2_address0),
    .ce0(A_2_ce0),
    .we0(A_2_we0),
    .d0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_2_d0),
    .q0(A_2_q0)
);

stream_matmul_A_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_3_address0),
    .ce0(A_3_ce0),
    .we0(A_3_we0),
    .d0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_3_d0),
    .q0(A_3_q0)
);

stream_matmul_A_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
B_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(B_address0),
    .ce0(B_ce0),
    .we0(B_we0),
    .d0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_d0),
    .q0(B_q0)
);

stream_matmul_A_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
B_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(B_1_address0),
    .ce0(B_1_ce0),
    .we0(B_1_we0),
    .d0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_1_d0),
    .q0(B_1_q0)
);

stream_matmul_A_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
B_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(B_2_address0),
    .ce0(B_2_ce0),
    .we0(B_2_we0),
    .d0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_2_d0),
    .q0(B_2_q0)
);

stream_matmul_A_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
B_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(B_3_address0),
    .ce0(B_3_ce0),
    .we0(B_3_we0),
    .d0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_3_d0),
    .q0(B_3_q0)
);

stream_matmul_C_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
C_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(C_address0),
    .ce0(C_ce0),
    .we0(C_we0),
    .d0(C_d0),
    .q0(C_q0)
);

stream_matmul_stream_matmul_Pipeline_init_c_i_init_c_j grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_ap_start),
    .ap_done(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_ap_done),
    .ap_idle(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_ap_idle),
    .ap_ready(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_ap_ready),
    .C_address0(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_C_address0),
    .C_ce0(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_C_ce0),
    .C_we0(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_C_we0),
    .C_d0(grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_C_d0)
);

stream_matmul_stream_matmul_Pipeline_read_a_i_read_a_j grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_ap_start),
    .ap_done(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_ap_done),
    .ap_idle(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_ap_idle),
    .ap_ready(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_ap_ready),
    .in_stream_TVALID(in_stream_TVALID_int_regslice),
    .A_address0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_address0),
    .A_ce0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_ce0),
    .A_we0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_we0),
    .A_d0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_d0),
    .A_1_address0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_1_address0),
    .A_1_ce0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_1_ce0),
    .A_1_we0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_1_we0),
    .A_1_d0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_1_d0),
    .A_2_address0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_2_address0),
    .A_2_ce0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_2_ce0),
    .A_2_we0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_2_we0),
    .A_2_d0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_2_d0),
    .A_3_address0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_3_address0),
    .A_3_ce0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_3_ce0),
    .A_3_we0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_3_we0),
    .A_3_d0(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_3_d0),
    .in_stream_TDATA(in_stream_TDATA_int_regslice),
    .in_stream_TREADY(grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_in_stream_TREADY),
    .in_stream_TKEEP(in_stream_TKEEP_int_regslice),
    .in_stream_TSTRB(in_stream_TSTRB_int_regslice),
    .in_stream_TLAST(in_stream_TLAST_int_regslice)
);

stream_matmul_stream_matmul_Pipeline_write_c_i_write_c_j grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_ap_start),
    .ap_done(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_ap_done),
    .ap_idle(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_ap_idle),
    .ap_ready(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_ap_ready),
    .out_stream_TREADY(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TREADY),
    .C_address0(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_C_address0),
    .C_ce0(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_C_ce0),
    .C_q0(C_q0),
    .out_stream_TDATA(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TDATA),
    .out_stream_TVALID(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TVALID),
    .out_stream_TKEEP(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TKEEP),
    .out_stream_TSTRB(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TSTRB),
    .out_stream_TLAST(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TLAST)
);

stream_matmul_stream_matmul_Pipeline_read_b_i_read_b_j grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_ap_start),
    .ap_done(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_ap_done),
    .ap_idle(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_ap_idle),
    .ap_ready(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_ap_ready),
    .in_stream_TVALID(in_stream_TVALID_int_regslice),
    .B_address0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_address0),
    .B_ce0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_ce0),
    .B_we0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_we0),
    .B_d0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_d0),
    .B_1_address0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_1_address0),
    .B_1_ce0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_1_ce0),
    .B_1_we0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_1_we0),
    .B_1_d0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_1_d0),
    .B_2_address0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_2_address0),
    .B_2_ce0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_2_ce0),
    .B_2_we0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_2_we0),
    .B_2_d0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_2_d0),
    .B_3_address0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_3_address0),
    .B_3_ce0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_3_ce0),
    .B_3_we0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_3_we0),
    .B_3_d0(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_3_d0),
    .in_stream_TDATA(in_stream_TDATA_int_regslice),
    .in_stream_TREADY(grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_in_stream_TREADY),
    .in_stream_TKEEP(in_stream_TKEEP_int_regslice),
    .in_stream_TSTRB(in_stream_TSTRB_int_regslice),
    .in_stream_TLAST(in_stream_TLAST_int_regslice)
);

stream_matmul_stream_matmul_Pipeline_compute_i_compute_j_compute_k grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_ap_start),
    .ap_done(grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_ap_done),
    .ap_idle(grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_ap_idle),
    .ap_ready(grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_ap_ready),
    .A_address0(grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_A_address0),
    .A_ce0(grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_A_ce0),
    .A_q0(A_q0),
    .A_1_address0(grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_A_1_address0),
    .A_1_ce0(grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_A_1_ce0),
    .A_1_q0(A_1_q0),
    .A_2_address0(grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_A_2_address0),
    .A_2_ce0(grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_A_2_ce0),
    .A_2_q0(A_2_q0),
    .A_3_address0(grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_A_3_address0),
    .A_3_ce0(grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_A_3_ce0),
    .A_3_q0(A_3_q0),
    .B_address0(grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_B_address0),
    .B_ce0(grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_B_ce0),
    .B_q0(B_q0),
    .B_1_address0(grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_B_1_address0),
    .B_1_ce0(grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_B_1_ce0),
    .B_1_q0(B_1_q0),
    .B_2_address0(grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_B_2_address0),
    .B_2_ce0(grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_B_2_ce0),
    .B_2_q0(B_2_q0),
    .B_3_address0(grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_B_3_address0),
    .B_3_ce0(grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_B_3_ce0),
    .B_3_q0(B_3_q0),
    .C_address0(grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_C_address0),
    .C_ce0(grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_C_ce0),
    .C_we0(grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_C_we0),
    .C_d0(grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_C_d0),
    .C_q0(C_q0)
);

stream_matmul_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .num_k_tiles(num_k_tiles),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

stream_matmul_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

stream_matmul_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

stream_matmul_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

stream_matmul_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int_regslice),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

stream_matmul_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TDATA_int_regslice),
    .vld_in(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TVALID),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

stream_matmul_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TKEEP_int_regslice),
    .vld_in(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

stream_matmul_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TSTRB_int_regslice),
    .vld_in(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

stream_matmul_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TLAST_int_regslice),
    .vld_in(grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state7) & (1'b1 == ap_CS_fsm_state6))) begin
            grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_ap_start_reg <= 1'b1;
        end else if ((grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_ap_ready == 1'b1)) begin
            grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_ap_start_reg <= 1'b1;
        end else if ((grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_ap_ready == 1'b1)) begin
            grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln99_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_ap_start_reg <= 1'b1;
        end else if ((grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_ap_ready == 1'b1)) begin
            grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_ap_start_reg <= 1'b1;
        end else if ((grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_ap_ready == 1'b1)) begin
            grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln99_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_ap_start_reg <= 1'b1;
        end else if ((grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_ap_ready == 1'b1)) begin
            grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        kk_fu_90 <= 32'd0;
    end else if (((icmp_ln99_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        kk_fu_90 <= add_ln99_fu_261_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TVALID == 1'b1))) begin
        out_stream_TDATA_reg <= grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TDATA;
        out_stream_TKEEP_reg <= grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TKEEP;
        out_stream_TLAST_reg <= grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TLAST;
        out_stream_TSTRB_reg <= grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TSTRB;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        select_ln99_1_reg_285 <= select_ln99_1_fu_245_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        select_ln99_reg_279 <= select_ln99_fu_222_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        A_1_address0 = grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_A_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        A_1_address0 = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_1_address0;
    end else begin
        A_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        A_1_ce0 = grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_A_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        A_1_ce0 = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_1_ce0;
    end else begin
        A_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_1_we0 = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_1_we0;
    end else begin
        A_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        A_2_address0 = grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_A_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        A_2_address0 = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_2_address0;
    end else begin
        A_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        A_2_ce0 = grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_A_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        A_2_ce0 = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_2_ce0;
    end else begin
        A_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_2_we0 = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_2_we0;
    end else begin
        A_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        A_3_address0 = grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_A_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        A_3_address0 = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_3_address0;
    end else begin
        A_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        A_3_ce0 = grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_A_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        A_3_ce0 = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_3_ce0;
    end else begin
        A_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_3_we0 = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_3_we0;
    end else begin
        A_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        A_address0 = grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_A_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        A_address0 = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_address0;
    end else begin
        A_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        A_ce0 = grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_A_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        A_ce0 = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_ce0;
    end else begin
        A_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_we0 = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_A_we0;
    end else begin
        A_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        B_1_address0 = grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_B_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_1_address0 = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_1_address0;
    end else begin
        B_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        B_1_ce0 = grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_B_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_1_ce0 = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_1_ce0;
    end else begin
        B_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        B_1_we0 = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_1_we0;
    end else begin
        B_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        B_2_address0 = grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_B_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_2_address0 = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_2_address0;
    end else begin
        B_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        B_2_ce0 = grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_B_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_2_ce0 = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_2_ce0;
    end else begin
        B_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        B_2_we0 = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_2_we0;
    end else begin
        B_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        B_3_address0 = grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_B_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_3_address0 = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_3_address0;
    end else begin
        B_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        B_3_ce0 = grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_B_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_3_ce0 = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_3_ce0;
    end else begin
        B_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        B_3_we0 = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_3_we0;
    end else begin
        B_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        B_address0 = grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_B_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_address0 = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_address0;
    end else begin
        B_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        B_ce0 = grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_B_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_ce0 = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_ce0;
    end else begin
        B_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        B_we0 = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_B_we0;
    end else begin
        B_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        C_address0 = grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_C_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        C_address0 = grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_C_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        C_address0 = grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_C_address0;
    end else begin
        C_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        C_ce0 = grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_C_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        C_ce0 = grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_C_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        C_ce0 = grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_C_ce0;
    end else begin
        C_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        C_d0 = grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_C_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        C_d0 = grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_C_d0;
    end else begin
        C_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        C_we0 = grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_C_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        C_we0 = grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_C_we0;
    end else begin
        C_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state10))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state10))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        in_stream_TREADY_int_regslice = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_in_stream_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        in_stream_TREADY_int_regslice = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_in_stream_TREADY;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TVALID == 1'b1))) begin
        out_stream_TDATA_int_regslice = grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TDATA;
    end else begin
        out_stream_TDATA_int_regslice = out_stream_TDATA_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TVALID == 1'b1))) begin
        out_stream_TKEEP_int_regslice = grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TKEEP;
    end else begin
        out_stream_TKEEP_int_regslice = out_stream_TKEEP_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TVALID == 1'b1))) begin
        out_stream_TLAST_int_regslice = grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TLAST;
    end else begin
        out_stream_TLAST_int_regslice = out_stream_TLAST_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TVALID == 1'b1))) begin
        out_stream_TSTRB_int_regslice = grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TSTRB;
    end else begin
        out_stream_TSTRB_int_regslice = out_stream_TSTRB_reg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln99_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln99_fu_261_p2 = (kk_fu_90 + 32'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_NS_fsm_state7 = ap_NS_fsm[32'd6];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign empty_fu_235_p2 = (($signed(select_ln99_reg_279) > $signed(32'd4294967231)) ? 1'b1 : 1'b0);

assign grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_ap_start = grp_stream_matmul_Pipeline_compute_i_compute_j_compute_k_fu_187_ap_start_reg;

assign grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_ap_start = grp_stream_matmul_Pipeline_init_c_i_init_c_j_fu_136_ap_start_reg;

assign grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_ap_start = grp_stream_matmul_Pipeline_read_a_i_read_a_j_fu_142_ap_start_reg;

assign grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_ap_start = grp_stream_matmul_Pipeline_read_b_i_read_b_j_fu_171_ap_start_reg;

assign grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_ap_start = grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_ap_start_reg;

assign grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TREADY = (out_stream_TREADY_int_regslice & ap_CS_fsm_state9);

assign icmp_fu_210_p2 = (($signed(tmp_fu_200_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln99_fu_256_p2 = ((kk_fu_90 == select_ln99_1_reg_285) ? 1'b1 : 1'b0);

assign in_stream_TREADY = regslice_both_in_stream_V_data_V_U_ack_in;

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign out_stream_TVALID_int_regslice = grp_stream_matmul_Pipeline_write_c_i_write_c_j_fu_158_out_stream_TVALID;

assign select_ln99_1_fu_245_p3 = ((empty_fu_235_p2[0:0] == 1'b1) ? xor_ln99_1_fu_240_p2 : 32'd64);

assign select_ln99_fu_222_p3 = ((icmp_fu_210_p2[0:0] == 1'b1) ? xor_ln99_fu_216_p2 : 32'd4294967294);

assign tmp_fu_200_p4 = {{num_k_tiles[31:1]}};

assign xor_ln99_1_fu_240_p2 = (select_ln99_reg_279 ^ 32'd4294967295);

assign xor_ln99_fu_216_p2 = (num_k_tiles ^ 32'd4294967295);

endmodule //stream_matmul
