transcript off
onbreak {quit -force}
onerror {quit -force}
transcript on

vlib work
vlib riviera/xilinx_vip
vlib riviera/xpm
vlib riviera/axi_infrastructure_v1_1_0
vlib riviera/axi_vip_v1_1_21
vlib riviera/processing_system7_vip_v1_0_23
vlib riviera/xil_defaultlib
vlib riviera/xbip_utils_v3_0_14
vlib riviera/axi_utils_v2_0_10
vlib riviera/xbip_pipe_v3_0_10
vlib riviera/xbip_dsp48_wrapper_v3_0_7
vlib riviera/mult_gen_v12_0_23
vlib riviera/floating_point_v7_1_20
vlib riviera/xlconstant_v1_1_10
vlib riviera/proc_sys_reset_v5_0_17
vlib riviera/smartconnect_v1_0
vlib riviera/axi_register_slice_v2_1_35
vlib riviera/axi_datamover_v5_1_37
vlib riviera/axi_sg_v4_1_21
vlib riviera/axi_dma_v7_1_36
vlib riviera/generic_baseblocks_v2_1_2
vlib riviera/fifo_generator_v13_2_13
vlib riviera/axi_data_fifo_v2_1_35
vlib riviera/axi_crossbar_v2_1_37
vlib riviera/axi_protocol_converter_v2_1_36

vmap xilinx_vip riviera/xilinx_vip
vmap xpm riviera/xpm
vmap axi_infrastructure_v1_1_0 riviera/axi_infrastructure_v1_1_0
vmap axi_vip_v1_1_21 riviera/axi_vip_v1_1_21
vmap processing_system7_vip_v1_0_23 riviera/processing_system7_vip_v1_0_23
vmap xil_defaultlib riviera/xil_defaultlib
vmap xbip_utils_v3_0_14 riviera/xbip_utils_v3_0_14
vmap axi_utils_v2_0_10 riviera/axi_utils_v2_0_10
vmap xbip_pipe_v3_0_10 riviera/xbip_pipe_v3_0_10
vmap xbip_dsp48_wrapper_v3_0_7 riviera/xbip_dsp48_wrapper_v3_0_7
vmap mult_gen_v12_0_23 riviera/mult_gen_v12_0_23
vmap floating_point_v7_1_20 riviera/floating_point_v7_1_20
vmap xlconstant_v1_1_10 riviera/xlconstant_v1_1_10
vmap proc_sys_reset_v5_0_17 riviera/proc_sys_reset_v5_0_17
vmap smartconnect_v1_0 riviera/smartconnect_v1_0
vmap axi_register_slice_v2_1_35 riviera/axi_register_slice_v2_1_35
vmap axi_datamover_v5_1_37 riviera/axi_datamover_v5_1_37
vmap axi_sg_v4_1_21 riviera/axi_sg_v4_1_21
vmap axi_dma_v7_1_36 riviera/axi_dma_v7_1_36
vmap generic_baseblocks_v2_1_2 riviera/generic_baseblocks_v2_1_2
vmap fifo_generator_v13_2_13 riviera/fifo_generator_v13_2_13
vmap axi_data_fifo_v2_1_35 riviera/axi_data_fifo_v2_1_35
vmap axi_crossbar_v2_1_37 riviera/axi_crossbar_v2_1_37
vmap axi_protocol_converter_v2_1_36 riviera/axi_protocol_converter_v2_1_36

vlog -work xilinx_vip  -incr "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_if.sv" \
"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/clk_vip_if.sv" \
"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm  -incr "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"/opt/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"/opt/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"/opt/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93  -incr \
"/opt/Xilinx/2025.1/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work axi_infrastructure_v1_1_0  -incr -v2k5 "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_vip_v1_1_21  -incr "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f16f/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work processing_system7_vip_v1_0_23  -incr "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_processing_system7_0_0/sim/design_1_processing_system7_0_0.v" \

vcom -work xbip_utils_v3_0_14 -93  -incr \
"../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/hdl/ip/stream_matmul_fadd_32ns_32ns_32_5_full_dsp_1_ip/hdl/xbip_utils_v3_0_vh_rfs.vhd" \

vcom -work axi_utils_v2_0_10 -93  -incr \
"../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/hdl/ip/stream_matmul_fadd_32ns_32ns_32_5_full_dsp_1_ip/hdl/axi_utils_v2_0_vh_rfs.vhd" \

vcom -work xbip_pipe_v3_0_10 -93  -incr \
"../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/hdl/ip/stream_matmul_fadd_32ns_32ns_32_5_full_dsp_1_ip/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \

vcom -work xbip_dsp48_wrapper_v3_0_7 -93  -incr \
"../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/hdl/ip/stream_matmul_fadd_32ns_32ns_32_5_full_dsp_1_ip/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \

vcom -work mult_gen_v12_0_23 -93  -incr \
"../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/hdl/ip/stream_matmul_fadd_32ns_32ns_32_5_full_dsp_1_ip/hdl/mult_gen_v12_0_vh_rfs.vhd" \

vcom -work floating_point_v7_1_20 -93  -incr \
"../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/hdl/ip/stream_matmul_fadd_32ns_32ns_32_5_full_dsp_1_ip/hdl/floating_point_v7_1_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/design_1/ip/design_1_stream_matmul_0_0/hdl/ip/stream_matmul_fadd_32ns_32ns_32_5_full_dsp_1_ip/sim/stream_matmul_fadd_32ns_32ns_32_5_full_dsp_1_ip.vhd" \
"../../../bd/design_1/ip/design_1_stream_matmul_0_0/hdl/ip/stream_matmul_fmul_32ns_32ns_32_4_max_dsp_1_ip/sim/stream_matmul_fmul_32ns_32ns_32_4_max_dsp_1_ip.vhd" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog/stream_matmul_A_RAM_AUTO_1R1W.v" \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog/stream_matmul_C_RAM_AUTO_1R1W.v" \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog/stream_matmul_control_s_axi.v" \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog/stream_matmul_fadd_32ns_32ns_32_5_full_dsp_1.v" \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog/stream_matmul_flow_control_loop_pipe_sequential_init.v" \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog/stream_matmul_fmul_32ns_32ns_32_4_max_dsp_1.v" \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog/stream_matmul_hls_deadlock_idx0_monitor.v" \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog/stream_matmul_regslice_both.v" \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog/stream_matmul_stream_matmul_Pipeline_VITIS_LOOP_55_1_VITIS_LOOP_56_2.v" \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog/stream_matmul_stream_matmul_Pipeline_VITIS_LOOP_66_4_VITIS_LOOP_67_5.v" \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog/stream_matmul_stream_matmul_Pipeline_VITIS_LOOP_74_6_VITIS_LOOP_75_7.v" \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog/stream_matmul_stream_matmul_Pipeline_VITIS_LOOP_83_8_VITIS_LOOP_84_9_VITIS_LOOP_87_10.v" \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog/stream_matmul_stream_matmul_Pipeline_VITIS_LOOP_98_11_VITIS_LOOP_99_12.v" \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog/stream_matmul.v" \
"../../../bd/design_1/ip/design_1_stream_matmul_0_0/sim/design_1_stream_matmul_0_0.v" \

vlog -work xlconstant_v1_1_10  -incr -v2k5 "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a165/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_0/sim/bd_afc3_one_0.v" \

vcom -work proc_sys_reset_v5_0_17 -93  -incr \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/9438/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/sim/bd_afc3_psr_aclk_0.vhd" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/3718/hdl/sc_switchboard_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_2/sim/bd_afc3_arinsw_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_3/sim/bd_afc3_rinsw_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_4/sim/bd_afc3_awinsw_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_5/sim/bd_afc3_winsw_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_6/sim/bd_afc3_binsw_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_7/sim/bd_afc3_aroutsw_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_8/sim/bd_afc3_routsw_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_9/sim/bd_afc3_awoutsw_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_10/sim/bd_afc3_woutsw_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_11/sim/bd_afc3_boutsw_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_12/sim/bd_afc3_arni_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_13/sim/bd_afc3_rni_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_14/sim/bd_afc3_awni_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_15/sim/bd_afc3_wni_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_16/sim/bd_afc3_bni_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/d800/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_17/sim/bd_afc3_s00mmu_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/2da8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_18/sim/bd_afc3_s00tr_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/dce3/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_19/sim/bd_afc3_s00sic_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/cef3/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_20/sim/bd_afc3_s00a2s_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_21/sim/bd_afc3_sarn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_22/sim/bd_afc3_srn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_23/sim/bd_afc3_sawn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_24/sim/bd_afc3_swn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_25/sim/bd_afc3_sbn_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/7f4f/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_26/sim/bd_afc3_m00s2a_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_27/sim/bd_afc3_m00arn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_28/sim/bd_afc3_m00rn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_29/sim/bd_afc3_m00awn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_30/sim/bd_afc3_m00wn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_31/sim/bd_afc3_m00bn_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/0133/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_32/sim/bd_afc3_m00e_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_33/sim/bd_afc3_m01s2a_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_34/sim/bd_afc3_m01arn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_35/sim/bd_afc3_m01rn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_36/sim/bd_afc3_m01awn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_37/sim/bd_afc3_m01wn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_38/sim/bd_afc3_m01bn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_39/sim/bd_afc3_m01e_0.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/sim/bd_afc3.v" \

vlog -work axi_register_slice_v2_1_35  -incr -v2k5 "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/c5b7/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_axi_smc_0/sim/design_1_axi_smc_0.sv" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/design_1/ip/design_1_rst_ps7_0_100M_0/sim/design_1_rst_ps7_0_100M_0.vhd" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../bd/design_1/sim/design_1.v" \

vcom -work axi_datamover_v5_1_37 -93  -incr \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/d44a/hdl/axi_datamover_v5_1_vh_rfs.vhd" \

vcom -work axi_sg_v4_1_21 -93  -incr \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/b193/hdl/axi_sg_v4_1_rfs.vhd" \

vcom -work axi_dma_v7_1_36 -93  -incr \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/cb19/hdl/axi_dma_v7_1_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/design_1/ip/design_1_axi_dma_0_3/sim/design_1_axi_dma_0_3.vhd" \

vlog -work generic_baseblocks_v2_1_2  -incr -v2k5 "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/0c28/hdl/generic_baseblocks_v2_1_vl_rfs.v" \

vlog -work fifo_generator_v13_2_13  -incr -v2k5 "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/dc46/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_2_13 -93  -incr \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/dc46/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -work fifo_generator_v13_2_13  -incr -v2k5 "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/dc46/hdl/fifo_generator_v13_2_rfs.v" \

vlog -work axi_data_fifo_v2_1_35  -incr -v2k5 "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/4846/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_crossbar_v2_1_37  -incr -v2k5 "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a1a7/hdl/axi_crossbar_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_axi_mem_intercon_imp_xbar_0/sim/design_1_axi_mem_intercon_imp_xbar_0.v" \

vlog -work axi_protocol_converter_v2_1_36  -incr -v2k5 "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/6583/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/drivers/stream_matmul_v1_0/src" "+incdir+/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_7 -l mult_gen_v12_0_23 -l floating_point_v7_1_20 -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_crossbar_v2_1_37 -l axi_protocol_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_axi_mem_intercon_imp_auto_pc_0/sim/design_1_axi_mem_intercon_imp_auto_pc_0.v" \
"../../../bd/design_1/ip/design_1_axi_mem_intercon_imp_auto_pc_1/sim/design_1_axi_mem_intercon_imp_auto_pc_1.v" \

vlog -work xil_defaultlib \
"glbl.v"

