-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity stream_matmul_stream_matmul_Pipeline_compute_k is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    acc : IN STD_LOGIC_VECTOR (31 downto 0);
    i_4 : IN STD_LOGIC_VECTOR (3 downto 0);
    A_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    A_ce0 : OUT STD_LOGIC;
    A_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    A_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    A_1_ce0 : OUT STD_LOGIC;
    A_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    A_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    A_2_ce0 : OUT STD_LOGIC;
    A_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    A_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    A_3_ce0 : OUT STD_LOGIC;
    A_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    zext_ln147 : IN STD_LOGIC_VECTOR (3 downto 0);
    B_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    B_ce0 : OUT STD_LOGIC;
    B_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    B_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    B_1_ce0 : OUT STD_LOGIC;
    B_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    B_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    B_2_ce0 : OUT STD_LOGIC;
    B_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    B_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    B_3_ce0 : OUT STD_LOGIC;
    B_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    acc_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_1_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of stream_matmul_stream_matmul_Pipeline_compute_k is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_7FFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "01111111111111111111111111111111";
    constant ap_const_lv32_80000000 : STD_LOGIC_VECTOR (31 downto 0) := "10000000000000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal tmp_reg_798 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage2 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_fu_238_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal A_load_reg_842 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal B_load_reg_847 : STD_LOGIC_VECTOR (15 downto 0);
    signal A_1_load_reg_852 : STD_LOGIC_VECTOR (15 downto 0);
    signal B_1_load_reg_857 : STD_LOGIC_VECTOR (15 downto 0);
    signal A_2_load_reg_862 : STD_LOGIC_VECTOR (15 downto 0);
    signal B_2_load_reg_867 : STD_LOGIC_VECTOR (15 downto 0);
    signal A_3_load_reg_872 : STD_LOGIC_VECTOR (15 downto 0);
    signal B_3_load_reg_877 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln1_reg_882 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal tmp_1_reg_887 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln153_2_reg_892 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_4_reg_897 : STD_LOGIC_VECTOR (0 downto 0);
    signal acc_3_fu_444_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_3_reg_902 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln153_2_fu_458_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal add_ln153_2_reg_908 : STD_LOGIC_VECTOR (24 downto 0);
    signal trunc_ln153_4_reg_914 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_7_reg_919 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln153_6_reg_924 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_10_reg_929 : STD_LOGIC_VECTOR (0 downto 0);
    signal acc_7_fu_680_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_7_reg_934 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln153_6_fu_694_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal add_ln153_6_reg_940 : STD_LOGIC_VECTOR (24 downto 0);
    signal zext_ln153_4_fu_264_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln153_5_fu_280_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal acc_1_fu_88 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal acc_9_fu_766_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal ap_loop_init : STD_LOGIC;
    signal k_fu_92 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln151_fu_288_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_k_1 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage2_01001 : BOOLEAN;
    signal A_ce0_local : STD_LOGIC;
    signal B_ce0_local : STD_LOGIC;
    signal A_1_ce0_local : STD_LOGIC;
    signal B_1_ce0_local : STD_LOGIC;
    signal A_2_ce0_local : STD_LOGIC;
    signal B_2_ce0_local : STD_LOGIC;
    signal A_3_ce0_local : STD_LOGIC;
    signal B_3_ce0_local : STD_LOGIC;
    signal lshr_ln2_fu_246_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_256_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln153_s_fu_272_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln153_fu_305_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln153_1_fu_335_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln153_16_fu_362_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal zext_ln153_fu_365_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal add_ln153_fu_368_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln153_2_fu_378_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln153_17_fu_374_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln153_8_fu_386_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln153_3_fu_382_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln153_2_fu_378_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln153_1_fu_392_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln153_8_fu_386_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_398_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_410_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln153_fu_418_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln153_fu_424_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln153_1_fu_430_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln153_fu_436_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_2_fu_406_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln153_18_fu_452_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal zext_ln153_1_fu_455_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln153_2_fu_470_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln153_3_fu_500_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal sext_ln153_19_fu_524_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln153_7_fu_530_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln153_6_fu_527_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln153_3_fu_538_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln153_9_fu_533_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_544_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_556_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln153_2_fu_564_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln153_1_fu_570_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln153_3_fu_576_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln153_2_fu_582_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_4_fu_552_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln153_20_fu_598_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal zext_ln153_2_fu_601_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal add_ln153_4_fu_604_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal acc_5_fu_590_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln153_21_fu_610_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln153_11_fu_618_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln153_10_fu_614_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln153_5_fu_628_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln153_10_fu_622_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_fu_634_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_646_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln153_4_fu_654_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln153_2_fu_660_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln153_5_fu_666_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln153_4_fu_672_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_6_fu_642_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln153_22_fu_688_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal zext_ln153_3_fu_691_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln153_23_fu_700_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln153_15_fu_706_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln153_14_fu_703_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln153_7_fu_714_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln153_11_fu_709_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_11_fu_720_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_732_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln153_6_fu_740_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln153_3_fu_746_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln153_7_fu_752_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln153_6_fu_758_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_8_fu_728_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component stream_matmul_mul_16s_16s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component stream_matmul_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_16s_16s_32_1_1_U21 : component stream_matmul_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => B_load_reg_847,
        din1 => A_load_reg_842,
        dout => mul_ln153_fu_305_p2);

    mul_16s_16s_32_1_1_U22 : component stream_matmul_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => B_1_load_reg_857,
        din1 => A_1_load_reg_852,
        dout => mul_ln153_1_fu_335_p2);

    mul_16s_16s_32_1_1_U23 : component stream_matmul_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => B_2_load_reg_867,
        din1 => A_2_load_reg_862,
        dout => mul_ln153_2_fu_470_p2);

    mul_16s_16s_32_1_1_U24 : component stream_matmul_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => B_3_load_reg_877,
        din1 => A_3_load_reg_872,
        dout => mul_ln153_3_fu_500_p2);

    flow_control_loop_pipe_sequential_init_U : component stream_matmul_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage2,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage2)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    acc_1_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                acc_1_fu_88 <= acc;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                acc_1_fu_88 <= acc_9_fu_766_p3;
            end if; 
        end if;
    end process;

    k_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (tmp_fu_238_p3 = ap_const_lv1_0))) then 
                    k_fu_92 <= add_ln151_fu_288_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_92 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                A_1_load_reg_852 <= A_1_q0;
                A_2_load_reg_862 <= A_2_q0;
                A_3_load_reg_872 <= A_3_q0;
                A_load_reg_842 <= A_q0;
                B_1_load_reg_857 <= B_1_q0;
                B_2_load_reg_867 <= B_2_q0;
                B_3_load_reg_877 <= B_3_q0;
                B_load_reg_847 <= B_q0;
                acc_7_reg_934 <= acc_7_fu_680_p3;
                add_ln153_6_reg_940 <= add_ln153_6_fu_694_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                acc_3_reg_902 <= acc_3_fu_444_p3;
                add_ln153_2_reg_908 <= add_ln153_2_fu_458_p2;
                tmp_10_reg_929 <= mul_ln153_3_fu_500_p2(7 downto 7);
                tmp_7_reg_919 <= mul_ln153_2_fu_470_p2(7 downto 7);
                tmp_reg_798 <= ap_sig_allocacmp_k_1(4 downto 4);
                trunc_ln153_4_reg_914 <= mul_ln153_2_fu_470_p2(31 downto 8);
                trunc_ln153_6_reg_924 <= mul_ln153_3_fu_500_p2(31 downto 8);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                tmp_1_reg_887 <= mul_ln153_fu_305_p2(7 downto 7);
                tmp_4_reg_897 <= mul_ln153_1_fu_335_p2(7 downto 7);
                trunc_ln153_2_reg_892 <= mul_ln153_1_fu_335_p2(31 downto 8);
                trunc_ln1_reg_882 <= mul_ln153_fu_305_p2(31 downto 8);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_idle_pp0, ap_block_pp0_stage2_subdone, ap_block_pp0_stage0_subdone, ap_block_pp0_stage1_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_idle_pp0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    A_1_address0 <= zext_ln153_4_fu_264_p1(6 - 1 downto 0);
    A_1_ce0 <= A_1_ce0_local;

    A_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            A_1_ce0_local <= ap_const_logic_1;
        else 
            A_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_2_address0 <= zext_ln153_4_fu_264_p1(6 - 1 downto 0);
    A_2_ce0 <= A_2_ce0_local;

    A_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            A_2_ce0_local <= ap_const_logic_1;
        else 
            A_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_3_address0 <= zext_ln153_4_fu_264_p1(6 - 1 downto 0);
    A_3_ce0 <= A_3_ce0_local;

    A_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            A_3_ce0_local <= ap_const_logic_1;
        else 
            A_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_address0 <= zext_ln153_4_fu_264_p1(6 - 1 downto 0);
    A_ce0 <= A_ce0_local;

    A_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            A_ce0_local <= ap_const_logic_1;
        else 
            A_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_1_address0 <= zext_ln153_5_fu_280_p1(6 - 1 downto 0);
    B_1_ce0 <= B_1_ce0_local;

    B_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            B_1_ce0_local <= ap_const_logic_1;
        else 
            B_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_2_address0 <= zext_ln153_5_fu_280_p1(6 - 1 downto 0);
    B_2_ce0 <= B_2_ce0_local;

    B_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            B_2_ce0_local <= ap_const_logic_1;
        else 
            B_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_3_address0 <= zext_ln153_5_fu_280_p1(6 - 1 downto 0);
    B_3_ce0 <= B_3_ce0_local;

    B_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            B_3_ce0_local <= ap_const_logic_1;
        else 
            B_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_address0 <= zext_ln153_5_fu_280_p1(6 - 1 downto 0);
    B_ce0 <= B_ce0_local;

    B_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            B_ce0_local <= ap_const_logic_1;
        else 
            B_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_1_out <= acc_1_fu_88;

    acc_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage2, tmp_reg_798, ap_loop_exit_ready, ap_block_pp0_stage2_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (tmp_reg_798 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            acc_1_out_ap_vld <= ap_const_logic_1;
        else 
            acc_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_2_fu_406_p1 <= add_ln153_1_fu_392_p2(32 - 1 downto 0);
    acc_3_fu_444_p3 <= 
        select_ln153_fu_436_p3 when (xor_ln153_1_fu_430_p2(0) = '1') else 
        acc_2_fu_406_p1;
    acc_4_fu_552_p1 <= add_ln153_3_fu_538_p2(32 - 1 downto 0);
    acc_5_fu_590_p3 <= 
        select_ln153_2_fu_582_p3 when (xor_ln153_3_fu_576_p2(0) = '1') else 
        acc_4_fu_552_p1;
    acc_6_fu_642_p1 <= add_ln153_5_fu_628_p2(32 - 1 downto 0);
    acc_7_fu_680_p3 <= 
        select_ln153_4_fu_672_p3 when (xor_ln153_5_fu_666_p2(0) = '1') else 
        acc_6_fu_642_p1;
    acc_8_fu_728_p1 <= add_ln153_7_fu_714_p2(32 - 1 downto 0);
    acc_9_fu_766_p3 <= 
        select_ln153_6_fu_758_p3 when (xor_ln153_7_fu_752_p2(0) = '1') else 
        acc_8_fu_728_p1;
    add_ln151_fu_288_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_k_1) + unsigned(ap_const_lv5_4));
    add_ln153_10_fu_622_p2 <= std_logic_vector(signed(sext_ln153_21_fu_610_p1) + signed(acc_5_fu_590_p3));
    add_ln153_11_fu_709_p2 <= std_logic_vector(signed(sext_ln153_23_fu_700_p1) + signed(acc_7_reg_934));
    add_ln153_1_fu_392_p2 <= std_logic_vector(signed(sext_ln153_3_fu_382_p1) + signed(sext_ln153_2_fu_378_p1));
    add_ln153_2_fu_458_p2 <= std_logic_vector(signed(sext_ln153_18_fu_452_p1) + signed(zext_ln153_1_fu_455_p1));
    add_ln153_3_fu_538_p2 <= std_logic_vector(signed(sext_ln153_7_fu_530_p1) + signed(sext_ln153_6_fu_527_p1));
    add_ln153_4_fu_604_p2 <= std_logic_vector(signed(sext_ln153_20_fu_598_p1) + signed(zext_ln153_2_fu_601_p1));
    add_ln153_5_fu_628_p2 <= std_logic_vector(signed(sext_ln153_11_fu_618_p1) + signed(sext_ln153_10_fu_614_p1));
    add_ln153_6_fu_694_p2 <= std_logic_vector(signed(sext_ln153_22_fu_688_p1) + signed(zext_ln153_3_fu_691_p1));
    add_ln153_7_fu_714_p2 <= std_logic_vector(signed(sext_ln153_15_fu_706_p1) + signed(sext_ln153_14_fu_703_p1));
    add_ln153_8_fu_386_p1 <= acc_1_fu_88;
    add_ln153_8_fu_386_p2 <= std_logic_vector(signed(sext_ln153_17_fu_374_p1) + signed(add_ln153_8_fu_386_p1));
    add_ln153_9_fu_533_p2 <= std_logic_vector(signed(sext_ln153_19_fu_524_p1) + signed(acc_3_reg_902));
    add_ln153_fu_368_p2 <= std_logic_vector(signed(sext_ln153_16_fu_362_p1) + signed(zext_ln153_fu_365_p1));
    add_ln153_s_fu_272_p3 <= (lshr_ln2_fu_246_p4 & zext_ln147);
    and_ln153_1_fu_570_p2 <= (xor_ln153_2_fu_564_p2 and tmp_6_fu_556_p3);
    and_ln153_2_fu_660_p2 <= (xor_ln153_4_fu_654_p2 and tmp_9_fu_646_p3);
    and_ln153_3_fu_746_p2 <= (xor_ln153_6_fu_740_p2 and tmp_12_fu_732_p3);
    and_ln153_fu_424_p2 <= (xor_ln153_fu_418_p2 and tmp_3_fu_410_p3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage2_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg, tmp_reg_798)
    begin
        if (((tmp_reg_798 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage2;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_k_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, k_fu_92)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_k_1 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_k_1 <= k_fu_92;
        end if; 
    end process;

    lshr_ln2_fu_246_p4 <= ap_sig_allocacmp_k_1(3 downto 2);
    select_ln153_2_fu_582_p3 <= 
        ap_const_lv32_7FFFFFFF when (and_ln153_1_fu_570_p2(0) = '1') else 
        ap_const_lv32_80000000;
    select_ln153_4_fu_672_p3 <= 
        ap_const_lv32_7FFFFFFF when (and_ln153_2_fu_660_p2(0) = '1') else 
        ap_const_lv32_80000000;
    select_ln153_6_fu_758_p3 <= 
        ap_const_lv32_7FFFFFFF when (and_ln153_3_fu_746_p2(0) = '1') else 
        ap_const_lv32_80000000;
    select_ln153_fu_436_p3 <= 
        ap_const_lv32_7FFFFFFF when (and_ln153_fu_424_p2(0) = '1') else 
        ap_const_lv32_80000000;
        sext_ln153_10_fu_614_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(acc_5_fu_590_p3),33));

        sext_ln153_11_fu_618_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln153_4_fu_604_p2),33));

        sext_ln153_14_fu_703_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(acc_7_reg_934),33));

        sext_ln153_15_fu_706_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln153_6_reg_940),33));

        sext_ln153_16_fu_362_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1_reg_882),25));

        sext_ln153_17_fu_374_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln153_fu_368_p2),32));

        sext_ln153_18_fu_452_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln153_2_reg_892),25));

        sext_ln153_19_fu_524_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln153_2_reg_908),32));

        sext_ln153_20_fu_598_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln153_4_reg_914),25));

        sext_ln153_21_fu_610_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln153_4_fu_604_p2),32));

        sext_ln153_22_fu_688_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln153_6_reg_924),25));

        sext_ln153_23_fu_700_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln153_6_reg_940),32));

    sext_ln153_2_fu_378_p0 <= acc_1_fu_88;
        sext_ln153_2_fu_378_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln153_2_fu_378_p0),33));

        sext_ln153_3_fu_382_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln153_fu_368_p2),33));

        sext_ln153_6_fu_527_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(acc_3_reg_902),33));

        sext_ln153_7_fu_530_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln153_2_reg_908),33));

    tmp_11_fu_720_p3 <= add_ln153_7_fu_714_p2(32 downto 32);
    tmp_12_fu_732_p3 <= add_ln153_11_fu_709_p2(31 downto 31);
    tmp_2_fu_398_p3 <= add_ln153_1_fu_392_p2(32 downto 32);
    tmp_3_fu_410_p3 <= add_ln153_8_fu_386_p2(31 downto 31);
    tmp_5_fu_544_p3 <= add_ln153_3_fu_538_p2(32 downto 32);
    tmp_6_fu_556_p3 <= add_ln153_9_fu_533_p2(31 downto 31);
    tmp_8_fu_634_p3 <= add_ln153_5_fu_628_p2(32 downto 32);
    tmp_9_fu_646_p3 <= add_ln153_10_fu_622_p2(31 downto 31);
    tmp_fu_238_p3 <= ap_sig_allocacmp_k_1(4 downto 4);
    tmp_s_fu_256_p3 <= (i_4 & lshr_ln2_fu_246_p4);
    xor_ln153_1_fu_430_p2 <= (tmp_3_fu_410_p3 xor tmp_2_fu_398_p3);
    xor_ln153_2_fu_564_p2 <= (tmp_5_fu_544_p3 xor ap_const_lv1_1);
    xor_ln153_3_fu_576_p2 <= (tmp_6_fu_556_p3 xor tmp_5_fu_544_p3);
    xor_ln153_4_fu_654_p2 <= (tmp_8_fu_634_p3 xor ap_const_lv1_1);
    xor_ln153_5_fu_666_p2 <= (tmp_9_fu_646_p3 xor tmp_8_fu_634_p3);
    xor_ln153_6_fu_740_p2 <= (tmp_11_fu_720_p3 xor ap_const_lv1_1);
    xor_ln153_7_fu_752_p2 <= (tmp_12_fu_732_p3 xor tmp_11_fu_720_p3);
    xor_ln153_fu_418_p2 <= (tmp_2_fu_398_p3 xor ap_const_lv1_1);
    zext_ln153_1_fu_455_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_reg_897),25));
    zext_ln153_2_fu_601_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_reg_919),25));
    zext_ln153_3_fu_691_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_reg_929),25));
    zext_ln153_4_fu_264_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_256_p3),64));
    zext_ln153_5_fu_280_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln153_s_fu_272_p3),64));
    zext_ln153_fu_365_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_reg_887),25));
end behav;
