domain_path: C:\Users\rodrigofonseca\Lab1-FixedPoint\platform\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: C:\AMDDesignTools\2025.2\Vitis\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
lang: c
