// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module stream_matmul_stream_matmul_Pipeline_read_b_i_read_b_j (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_TVALID,
        B_address0,
        B_ce0,
        B_we0,
        B_d0,
        B_1_address0,
        B_1_ce0,
        B_1_we0,
        B_1_d0,
        B_2_address0,
        B_2_ce0,
        B_2_we0,
        B_2_d0,
        B_3_address0,
        B_3_ce0,
        B_3_we0,
        B_3_d0,
        in_stream_TDATA,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_stream_TVALID;
output  [5:0] B_address0;
output   B_ce0;
output   B_we0;
output  [15:0] B_d0;
output  [5:0] B_1_address0;
output   B_1_ce0;
output   B_1_we0;
output  [15:0] B_1_d0;
output  [5:0] B_2_address0;
output   B_2_ce0;
output   B_2_we0;
output  [15:0] B_2_d0;
output  [5:0] B_3_address0;
output   B_3_ce0;
output   B_3_we0;
output  [15:0] B_3_d0;
input  [31:0] in_stream_TDATA;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;

reg ap_idle;
reg in_stream_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln132_fu_172_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    ap_block_pp0_stage0_11001;
wire   [1:0] trunc_ln132_fu_223_p1;
reg   [1:0] trunc_ln132_reg_325;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [5:0] add_ln137_fu_249_p2;
reg   [5:0] add_ln137_reg_329;
wire   [63:0] zext_ln137_1_fu_281_p1;
reg   [4:0] j_fu_78;
wire   [4:0] add_ln134_fu_265_p2;
wire    ap_loop_init;
reg   [4:0] i_fu_82;
wire   [4:0] select_ln132_fu_215_p3;
reg   [8:0] indvar_flatten13_fu_86;
wire   [8:0] add_ln132_1_fu_178_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten13_load;
wire    ap_block_pp0_stage0;
reg    B_2_we0_local;
wire   [15:0] value_fu_292_p1;
reg    B_2_ce0_local;
reg    B_1_we0_local;
reg    B_1_ce0_local;
reg    B_we0_local;
reg    B_ce0_local;
reg    B_3_we0_local;
reg    B_3_ce0_local;
wire   [0:0] icmp_ln134_fu_201_p2;
wire   [4:0] add_ln132_fu_195_p2;
wire   [1:0] lshr_ln84_2_fu_227_p4;
wire   [4:0] select_ln84_fu_207_p3;
wire   [5:0] tmp_s_fu_237_p3;
wire   [5:0] zext_ln137_fu_245_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 j_fu_78 = 5'd0;
#0 i_fu_82 = 5'd0;
#0 indvar_flatten13_fu_86 = 9'd0;
#0 ap_done_reg = 1'b0;
end

stream_matmul_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_82 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_fu_82 <= select_ln132_fu_215_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln132_fu_172_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten13_fu_86 <= add_ln132_1_fu_178_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten13_fu_86 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_78 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            j_fu_78 <= add_ln134_fu_265_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln137_reg_329 <= add_ln137_fu_249_p2;
        trunc_ln132_reg_325 <= trunc_ln132_fu_223_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_1_ce0_local = 1'b1;
    end else begin
        B_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln132_reg_325 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_1_we0_local = 1'b1;
    end else begin
        B_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_2_ce0_local = 1'b1;
    end else begin
        B_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln132_reg_325 == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_2_we0_local = 1'b1;
    end else begin
        B_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_3_ce0_local = 1'b1;
    end else begin
        B_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln132_reg_325 == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_3_we0_local = 1'b1;
    end else begin
        B_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_ce0_local = 1'b1;
    end else begin
        B_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln132_reg_325 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_we0_local = 1'b1;
    end else begin
        B_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln132_fu_172_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten13_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten13_load = indvar_flatten13_fu_86;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        in_stream_TREADY = 1'b1;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B_1_address0 = zext_ln137_1_fu_281_p1;

assign B_1_ce0 = B_1_ce0_local;

assign B_1_d0 = value_fu_292_p1;

assign B_1_we0 = B_1_we0_local;

assign B_2_address0 = zext_ln137_1_fu_281_p1;

assign B_2_ce0 = B_2_ce0_local;

assign B_2_d0 = value_fu_292_p1;

assign B_2_we0 = B_2_we0_local;

assign B_3_address0 = zext_ln137_1_fu_281_p1;

assign B_3_ce0 = B_3_ce0_local;

assign B_3_d0 = value_fu_292_p1;

assign B_3_we0 = B_3_we0_local;

assign B_address0 = zext_ln137_1_fu_281_p1;

assign B_ce0 = B_ce0_local;

assign B_d0 = value_fu_292_p1;

assign B_we0 = B_we0_local;

assign add_ln132_1_fu_178_p2 = (ap_sig_allocacmp_indvar_flatten13_load + 9'd1);

assign add_ln132_fu_195_p2 = (i_fu_82 + 5'd1);

assign add_ln134_fu_265_p2 = (select_ln84_fu_207_p3 + 5'd1);

assign add_ln137_fu_249_p2 = (tmp_s_fu_237_p3 + zext_ln137_fu_245_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((in_stream_TVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((in_stream_TVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((in_stream_TVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln132_fu_172_p2 = ((ap_sig_allocacmp_indvar_flatten13_load == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln134_fu_201_p2 = ((j_fu_78 == 5'd16) ? 1'b1 : 1'b0);

assign lshr_ln84_2_fu_227_p4 = {{select_ln132_fu_215_p3[3:2]}};

assign select_ln132_fu_215_p3 = ((icmp_ln134_fu_201_p2[0:0] == 1'b1) ? add_ln132_fu_195_p2 : i_fu_82);

assign select_ln84_fu_207_p3 = ((icmp_ln134_fu_201_p2[0:0] == 1'b1) ? 5'd0 : j_fu_78);

assign tmp_s_fu_237_p3 = {{lshr_ln84_2_fu_227_p4}, {4'd0}};

assign trunc_ln132_fu_223_p1 = select_ln132_fu_215_p3[1:0];

assign value_fu_292_p1 = in_stream_TDATA[15:0];

assign zext_ln137_1_fu_281_p1 = add_ln137_reg_329;

assign zext_ln137_fu_245_p1 = select_ln84_fu_207_p3;

endmodule //stream_matmul_stream_matmul_Pipeline_read_b_i_read_b_j
