# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/HWSW/project_matmul/project_matmul.srcs/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/design_1_stream_matmul_0_0.xci
# IP: The module: 'design_1_stream_matmul_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/HWSW/project_matmul/project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/hdl/ip/stream_matmul_fadd_32ns_32ns_32_5_full_dsp_1_ip/stream_matmul_fadd_32ns_32ns_32_5_full_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stream_matmul_fadd_32ns_32ns_32_5_full_dsp_1_ip || ORIG_REF_NAME==stream_matmul_fadd_32ns_32ns_32_5_full_dsp_1_ip} -quiet] -quiet

# IP: d:/HWSW/project_matmul/project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/hdl/ip/stream_matmul_fmul_32ns_32ns_32_4_max_dsp_1_ip/stream_matmul_fmul_32ns_32ns_32_4_max_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stream_matmul_fmul_32ns_32ns_32_4_max_dsp_1_ip || ORIG_REF_NAME==stream_matmul_fmul_32ns_32ns_32_4_max_dsp_1_ip} -quiet] -quiet

# XDC: d:/HWSW/project_matmul/project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/constraints/stream_matmul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_stream_matmul_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/HWSW/project_matmul/project_matmul.srcs/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/design_1_stream_matmul_0_0.xci
# IP: The module: 'design_1_stream_matmul_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/HWSW/project_matmul/project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/hdl/ip/stream_matmul_fadd_32ns_32ns_32_5_full_dsp_1_ip/stream_matmul_fadd_32ns_32ns_32_5_full_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stream_matmul_fadd_32ns_32ns_32_5_full_dsp_1_ip || ORIG_REF_NAME==stream_matmul_fadd_32ns_32ns_32_5_full_dsp_1_ip} -quiet] -quiet

# IP: d:/HWSW/project_matmul/project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/hdl/ip/stream_matmul_fmul_32ns_32ns_32_4_max_dsp_1_ip/stream_matmul_fmul_32ns_32ns_32_4_max_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stream_matmul_fmul_32ns_32ns_32_4_max_dsp_1_ip || ORIG_REF_NAME==stream_matmul_fmul_32ns_32ns_32_4_max_dsp_1_ip} -quiet] -quiet

# XDC: d:/HWSW/project_matmul/project_matmul.gen/sources_1/bd/design_1/ip/design_1_stream_matmul_0_0/constraints/stream_matmul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_stream_matmul_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
